# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.box_version = "1.0.282"
    config.vm.hostname = "NFSClient"
    config.vm.network "public_network", bridge: "wlp7s0"
    config.vm.network "private_network", ip: "192.168.10.11"
    config.vm.provision "shell", privileged: true, path: "bootstrap.sh"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "nfs-client"
        vb.memory = 1024
    end
end
